export { WizardContainer } from "./WizardContainer"
export { Paso1Solicitante } from "./Paso1Solicitante"
export { Paso2Inmueble } from "./Paso2Inmueble"
export { Paso3Solicitudes } from "./Paso3Solicitudes"
export { Paso4Adjuntos } from "./Paso4Adjuntos"
